Fix timestamp
SevenTV/ExtensionV3 pull request #83
Opened 2023-01-28 05:07 UTC by kelvinc6

Set the timestamp when configuring a `ChatMessage`.

2023-01-28 10:31 UTC, Excellify requested changes

2023-01-28 10:31 UTC, Excellify commented on src/site/twitch.tv/modules/chat/ChatList.vue
> +	if (msgData.t) msg.setTimeStamp(msgData.t);
t is when we recieve the message not when the message was sent. Twitch.ChatMessage has a timestamp which is what we want to use here

2023-01-28 10:40 UTC, AnatoleAM requested changes

2023-01-28 10:40 UTC, AnatoleAM commented on src/common/chat/ChatMessage.ts
> +	public setTimeStamp(time: number) {
nit: `setTimestamp`

```suggestion
	public setTimestamp(time: number) {
```

2023-01-28 16:35 UTC, kelvinc6 commented on src/site/twitch.tv/modules/chat/ChatList.vue
> +	if (msgData.t) msg.setTimeStamp(msgData.t);
Added a check for `Twitch.ChatMessage` let me know if this is what you meant.

2023-01-28 17:22 UTC, Excellify commented on src/site/twitch.tv/modules/chat/ChatList.vue
> +	if (msgData.t) msg.setTimeStamp(msgData.t);
the msgData can be any of twitch's messagetypes, if the messagetype is 0, ie a normal chat message, then this will work. but for any other type that also has a userMessage part the message will be located in msgData.message.timestamp

2023-01-28 17:23 UTC, Excellify commented on src/site/twitch.tv/modules/chat/ChatList.vue
> +	if (msgData.t) msg.setTimeStamp(msgData.t);
So both msgData.timestamp and msgData.message.timestamp needs to be checked

2023-01-28 17:24 UTC, Excellify commented
Install prettier/eslint or run yarn lint to check linting

2023-01-29 13:31 UTC, Excellify approved these changes
This seems to work fine

2023-01-30 12:42 UTC, AnatoleAM approved these changes

2023-01-30 12:42 UTC, merged