Vod support
SevenTV/ExtensionV3 pull request #86
Opened 2023-01-30 17:49 UTC by Excellify

2023-01-31 04:34 UTC, AnatoleAM requested changes
General issue: doesn't load during regular navigation, need to refresh the entire page

2023-01-31 04:34 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodChat.vue
> +		id: video.owner.id,
`video.owner` is sometimes null and this crashes the page

2023-01-31 04:34 UTC, AnatoleAM commented on src/site/twitch.tv/modules/chat-data/ChatDataModule.vue
> +
Why? This appears to serve no purpose

2023-01-31 04:34 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodChat.vue
> +	</Teleport>
This shouldn't need to be a thing. Adapt the vod message type to work with the existing chatlist renderer

2023-01-31 04:34 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodMessage.vue
> +	displayName: props.vodMsg.author.displayName,
I am unable to comprehend why this is a thing? Why all this duplicate code when you could've simply adapted twitch's vod message type to fit with the existing tokenizer.

2023-01-31 04:34 UTC, AnatoleAM commented on src/types/module.d.ts
> +	"chat-data": typeof ChatDataModuleVue;
Not sure what is the point of splitting "ChatData" into a new module

2023-01-31 04:37 UTC, AnatoleAM commented
tl;dr

- take out all the extra components you made
- instead, adapt the data from "comments" so they can be passed through the `onMessage()` in `ChatList.vue`
- then just modify the teleport logic so it fits onto the vod container

It should be possible to reduce this PR to like <200 lines of diff

2023-01-31 06:33 UTC, Excellify commented on src/types/module.d.ts
> +	"chat-data": typeof ChatDataModuleVue;
Because chatController, chatList and chatRoom are not components when viewing a vod. So the chat-module dosnt load at all

2023-01-31 06:42 UTC, Excellify commented on src/site/twitch.tv/modules/vod-chat/VodMessage.vue
> +	displayName: props.vodMsg.author.displayName,
Wdym, im using the tokenizer, but i need to build the message body from the msg tokens?

2023-01-31 06:43 UTC, Excellify commented on src/types/module.d.ts
> +	"chat-data": typeof ChatDataModuleVue;
So that emotes can be fetched in places where the components that the chat module uses are unavailable

2023-01-31 13:19 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodMessage.vue
> +	displayName: props.vodMsg.author.displayName,
in what way is there any code reusing here?  all I see is the same stuff copy pasted, this should be a 100 line diff branch

2023-01-31 13:21 UTC, AnatoleAM commented on src/types/module.d.ts
> +	"chat-data": typeof ChatDataModuleVue;
why not just change the condition in the chatmodule so it can match either scenario?

2023-01-31 14:06 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodChat.vue
> +		nextTick(scroller.scrollToLive);
Scrolling to live on every prop update will lead to excessive reflows

2023-01-31 14:06 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodChat.vue
> +	chatProperties.twitchBadgeSets = props.controller.component.badgeSets;
There is no guarantee badges would be populated by mount time?

2023-01-31 14:06 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodMessage.vue
> +	vodMsg: Twitch.VideoChatCommentContext;
This should be our own message instance type

2023-01-31 14:06 UTC, AnatoleAM commented on src/site/twitch.tv/modules/vod-chat/VodMessage.vue
> +}
Move this to `VodChat.vue`

2023-02-11 13:58 UTC, AnatoleAM commented
Superseded by #104

2023-02-11 13:58 UTC, closed without merging