Update inputs styles
SevenTV/ExtensionV3 pull request #90
Opened 2023-01-31 16:21 UTC by loczek

![Screenshot_20230131_050157](https://user-images.githubusercontent.com/30776250/215817585-6672532c-4201-4183-bae0-f4ca45a32fe4.png) ![Screenshot_20230131_050239](https://user-images.githubusercontent.com/30776250/215817612-cde21951-130f-4656-a27e-5fa5c368425d.png)

2023-01-31 16:26 UTC, ayyybubu commented
Looks very clean. The toggle switch could maybe use the same color as the 7tv logo #29b6f6

2023-02-01 14:40 UTC, AnatoleAM requested changes

2023-02-01 14:40 UTC, AnatoleAM commented on src/site/twitch.tv/modules/settings/components/Toggle.vue
> +	border-radius: 10rem;
`border-radius` should be no more than `0.25rem`

2023-02-01 14:40 UTC, AnatoleAM commented on src/site/twitch.tv/modules/settings/components/Toggle.vue
> +	border-radius: 10rem;
`border-radius` should be no more than `0.25rem`

2023-02-06 20:47 UTC, Melonify commented on src/site/twitch.tv/modules/settings/components/Toggle.vue
> +	border-radius: 10rem;
`border-radius` here isn't used to actually define the corner rounds, its just a high value to force the end caps to be circular instead of square on the ends of the bars, and the slider.

I think a high border radius is acceptable here, a square slider handle would look kinda odd imo.

2023-02-18 16:12 UTC, AnatoleAM approved these changes
This is pretty nice, only issue is I found the inputs lack contrast with the regular background and the thumb for the sliders felt a little dull / difficult to see.

Since this pull request has been hanging for quite a while I've made some quick tweaks, fixing these issues I highlighted and also keeping the `border-radius` usage limited to our `0.25rem` value to retain the "sharp"/"blocky" feel of the overall 7TV design scheme.

---

![image](https://user-images.githubusercontent.com/9599344/219875314-cb737f7f-2731-465d-8d04-2030628345d2.png)
![image](https://user-images.githubusercontent.com/9599344/219875591-2fa7cab9-b38a-4f3b-a540-ede1e04a767a.png)

Also added a subtle scale animation on the slider thumb when it's held/released for feedback, and brought a few things up to current standards.

Thanks for your contribution :+1:

2023-02-18 16:17 UTC, merged